spring.application.name=crypto-tracker

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/cryptotracker

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=crypto-tracker-group
spring.kafka.consumer.auto-offset-reset=latest

# Logging
logging.level.com.cryptotracker=INFO
logging.level.org.apache.kafka=WARN

# Server
server.port=8080
